import { CategoryEnum, ICategoryItem, ProductListType } from './MockData.types';

// created by GPT
export const productList: ProductListType = {
  'clothesAndShoes': [
    {
      'id': 1,
      'name': 'Кроссовки Nike',
      'description': 'Удобные кроссовки для повседневной носки',
      'category': 'clothesAndShoes',
      'price': 5999,
      'quantityOfGoods': 10,
      'productRating': 4.5,
      'image': 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?ixlib=rb-1.2.1&auto=format&fit=crop&w=500&q=60',
    },
    {
      'id': 2,
      'name': 'Куртка зимняя',
      'description': 'Теплая куртка с подкладкой',
      'category': 'clothesAndShoes',
      'price': 8999,
      'quantityOfGoods': 7,
      'productRating': 4.8,
      'image': 'https://images.unsplash.com/photo-1551232864-3f0890e580d9?ixlib=rb-1.2.1&auto=format&fit=crop&w=500&q=60',
    },
    {
      'id': 3,
      'name': 'Футболка белая',
      'description': 'Хлопковая футболка',
      'category': 'clothesAndShoes',
      'price': 799,
      'quantityOfGoods': 50,
      'productRating': 4.2,
      'image': 'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?ixlib=rb-1.2.1&auto=format&fit=crop&w=500&q=60',
    },
    {
      'id': 4,
      'name': 'Джинсы мужские',
      'description': 'Классические джинсы',
      'category': 'clothesAndShoes',
      'price': 2999,
      'quantityOfGoods': 20,
      'productRating': 4.4,
      'image': 'https://images.unsplash.com/photo-1542272604-787c3835535d?ixlib=rb-1.2.1&auto=format&fit=crop&w=500&q=60',
    },
    {
      'id': 5,
      'name': 'Ботинки кожаные',
      'description': 'Натуральная кожа, зимние',
      'category': 'clothesAndShoes',
      'price': 6999,
      'quantityOfGoods': 5,
      'productRating': 4.7,
      'image': 'https://images.unsplash.com/photo-1463100099107-aa0980c362e6?ixlib=rb-1.2.1&auto=format&fit=crop&w=500&q=60',
    },
  ],
  'householdGoods': [
    {
      'id': 6,
      'name': 'Швабра с отжимом',
      'description': 'Для удобной уборки пола',
      'category': 'householdGoods',
      'price': 1299,
      'quantityOfGoods': 12,
      'productRating': 4.3,
      'image': 'https://via.placeholder.com/500?text=Швабра+с+отжимом',
    },
    {
      'id': 7,
      'name': 'Набор губок',
      'description': '5 штук для мытья посуды',
      'category': 'householdGoods',
      'price': 199,
      'quantityOfGoods': 100,
      'productRating': 4.1,
      'image': 'https://via.placeholder.com/500?text=Набор+губок',
    },
    {
      'id': 8,
      'name': 'Корзина для белья',
      'description': 'Пластиковая корзина 45л',
      'category': 'householdGoods',
      'price': 899,
      'quantityOfGoods': 15,
      'productRating': 4.6,
      'image': 'https://via.placeholder.com/500?text=Корзина+для+белья',
    },
    {
      'id': 9,
      'name': 'Контейнеры для хранения',
      'description': 'Набор из 3 контейнеров',
      'category': 'householdGoods',
      'price': 499,
      'quantityOfGoods': 25,
      'productRating': 4.4,
      'image': 'https://via.placeholder.com/500?text=Контейнеры+для+хранения',
    },
    {
      'id': 10,
      'name': 'Сушилка для белья',
      'description': 'Складная сушилка, 20м',
      'category': 'householdGoods',
      'price': 1799,
      'quantityOfGoods': 8,
      'productRating': 4.5,
      'image': 'https://via.placeholder.com/500?text=Сушилка+для+белья',
    },
  ],
  'electronics': [
    {
      'id': 11,
      'name': 'Смартфон Samsung',
      'description': '128Гб, черный',
      'category': 'electronics',
      'price': 25999,
      'quantityOfGoods': 30,
      'productRating': 4.8,
      'image': 'https://images.unsplash.com/photo-1555774698-0b77e0d5fac6?ixlib=rb-1.2.1&auto=format&fit=crop&w=500&q=60',
    },
    {
      'id': 12,
      'name': 'Наушники Bluetooth',
      'description': 'Беспроводные с шумоподавлением',
      'category': 'electronics',
      'price': 3999,
      'quantityOfGoods': 50,
      'productRating': 4.6,
      'image': 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?ixlib=rb-1.2.1&auto=format&fit=crop&w=500&q=60',
    },
    {
      'id': 13,
      'name': 'Повербанк 10000мАч',
      'description': 'Компактный и мощный',
      'category': 'electronics',
      'price': 1499,
      'quantityOfGoods': 80,
      'productRating': 4.3,
      'image': 'https://via.placeholder.com/500?text=Повербанк+10000мАч',
    },
    {
      'id': 14,
      'name': 'Монитор 24"',
      'description': 'FullHD монитор',
      'category': 'electronics',
      'price': 7499,
      'quantityOfGoods': 18,
      'productRating': 4.7,
      'image': 'https://images.unsplash.com/photo-1546538915-a9e2c8d0a8e6?ixlib=rb-1.2.1&auto=format&fit=crop&w=500&q=60',
    },
    {
      'id': 15,
      'name': 'Клавиатура механическая',
      'description': 'RGB подсветка',
      'category': 'electronics',
      'price': 2999,
      'quantityOfGoods': 25,
      'productRating': 4.5,
      'image': 'https://images.unsplash.com/photo-1587829741301-dc798b83add3?ixlib=rb-1.2.1&auto=format&fit=crop&w=500&q=60',
    },
  ],
  'householdAppliances': [
    {
      'id': 16,
      'name': 'Микроволновка',
      'description': '20л, с грилем',
      'category': 'householdAppliances',
      'price': 5999,
      'quantityOfGoods': 10,
      'productRating': 4.5,
      'image': 'https://images.unsplash.com/photo-1599487488170-d11ec9c172f0?ixlib=rb-1.2.1&auto=format&fit=crop&w=500&q=60',
    },
    {
      'id': 17,
      'name': 'Пылесос циклонный',
      'description': 'Мощный и компактный',
      'category': 'householdAppliances',
      'price': 7999,
      'quantityOfGoods': 8,
      'productRating': 4.6,
      'image': 'https://via.placeholder.com/500?text=Пылесос+циклонный',
    },
    {
      'id': 18,
      'name': 'Утюг с паром',
      'description': 'Быстрый нагрев',
      'category': 'householdAppliances',
      'price': 2499,
      'quantityOfGoods': 15,
      'productRating': 4.2,
      'image': 'https://via.placeholder.com/500?text=Утюг+с+паром',
    },
    {
      'id': 19,
      'name': 'Хлебопечка',
      'description': '12 программ, таймер',
      'category': 'householdAppliances',
      'price': 5999,
      'quantityOfGoods': 6,
      'productRating': 4.4,
      'image': 'https://via.placeholder.com/500?text=Хлебопечка',
    },
    {
      'id': 20,
      'name': 'Электрочайник',
      'description': '1.7л, автоотключение',
      'category': 'householdAppliances',
      'price': 1999,
      'quantityOfGoods': 20,
      'productRating': 4.7,
      'image': 'https://images.unsplash.com/photo-1606755456206-b25206bfa433?ixlib=rb-1.2.1&auto=format&fit=crop&w=500&q=60',
    },
  ],
  'goodsForChildren': [
    {
      'id': 21,
      'name': 'Коляска прогулочная',
      'description': 'Легкая и складная',
      'category': 'goodsForChildren',
      'price': 8999,
      'quantityOfGoods': 5,
      'productRating': 4.6,
      'image': 'https://images.unsplash.com/photo-1564078516393-cf04bd966897?ixlib=rb-1.2.1&auto=format&fit=crop&w=500&q=60',
    },
    {
      'id': 22,
      'name': 'Пеленки одноразовые',
      'description': '60x60, упаковка 30шт',
      'category': 'goodsForChildren',
      'price': 799,
      'quantityOfGoods': 40,
      'productRating': 4.3,
      'image': 'https://via.placeholder.com/500?text=Пеленки+одноразовые',
    },
    {
      'id': 23,
      'name': 'Игрушка развивающая',
      'description': 'Музыкальная с огоньками',
      'category': 'goodsForChildren',
      'price': 1499,
      'quantityOfGoods': 20,
      'productRating': 4.5,
      'image': 'https://images.unsplash.com/photo-1596461404969-9ae70f2830c1?ixlib=rb-1.2.1&auto=format&fit=crop&w=500&q=60',
    },
    {
      'id': 24,
      'name': 'Стульчик для кормления',
      'description': 'Съемный поднос, компактный',
      'category': 'goodsForChildren',
      'price': 3999,
      'quantityOfGoods': 10,
      'productRating': 4.4,
      'image': 'https://via.placeholder.com/500?text=Стульчик+для+кормления',
    },
    {
      'id': 25,
      'name': 'Ночник детский',
      'description': 'Проектор звездного неба',
      'category': 'goodsForChildren',
      'price': 999,
      'quantityOfGoods': 30,
      'productRating': 4.6,
      'image': 'https://via.placeholder.com/500?text=Ночник+детский',
    },
  ],
  'constructionAndRenovation': [
    {
      'id': 26,
      'name': 'Перфоратор Bosch',
      'description': 'Мощный инструмент для ремонта',
      'category': 'constructionAndRenovation',
      'price': 9999,
      'quantityOfGoods': 12,
      'productRating': 4.7,
      'image': 'https://images.unsplash.com/photo-1586985289688-ca3cf47d3e6e?ixlib=rb-1.2.1&auto=format&fit=crop&w=500&q=60',
    },
    {
      'id': 27,
      'name': 'Обои виниловые',
      'description': 'Рулон 10м, с узором',
      'category': 'constructionAndRenovation',
      'price': 599,
      'quantityOfGoods': 40,
      'productRating': 4.4,
      'image': 'https://via.placeholder.com/500?text=Обои+виниловые',
    },
    {
      'id': 28,
      'name': 'Краска интерьерная',
      'description': '10л, белая',
      'category': 'constructionAndRenovation',
      'price': 1299,
      'quantityOfGoods': 30,
      'productRating': 4.5,
      'image': 'https://via.placeholder.com/500?text=Краска+интерьерная',
    },
    {
      'id': 29,
      'name': 'Плитка керамическая',
      'description': '20x20, упаковка 1.2м²',
      'category': 'constructionAndRenovation',
      'price': 899,
      'quantityOfGoods': 50,
      'productRating': 4.6,
      'image': 'https://via.placeholder.com/500?text=Плитка+керамическая',
    },
    {
      'id': 30,
      'name': 'Герметик силиконовый',
      'description': 'Белый, тюбик 300мл',
      'category': 'constructionAndRenovation',
      'price': 299,
      'quantityOfGoods': 60,
      'productRating': 4.2,
      'image': 'https://via.placeholder.com/500?text=Герметик+силиконовый',
    },
  ],
  'furniture': [
    {
      'id': 31,
      'name': 'Стол письменный',
      'description': 'Деревянный, 120x60',
      'category': 'furniture',
      'price': 5999,
      'quantityOfGoods': 10,
      'productRating': 4.5,
      'image': 'https://images.unsplash.com/photo-1518455027359-f3f8164ba6bd?ixlib=rb-1.2.1&auto=format&fit=crop&w=500&q=60',
    },
    {
      'id': 32,
      'name': 'Кресло офисное',
      'description': 'С эргономичной спинкой',
      'category': 'furniture',
      'price': 4999,
      'quantityOfGoods': 8,
      'productRating': 4.6,
      'image': 'https://images.unsplash.com/photo-1598300042247-d088f8ab3a91?ixlib=rb-1.2.1&auto=format&fit=crop&w=500&q=60',
    },
    {
      'id': 33,
      'name': 'Шкаф 3-дверный',
      'description': 'С зеркалом и полками',
      'category': 'furniture',
      'price': 10999,
      'quantityOfGoods': 5,
      'productRating': 4.7,
      'image': 'https://via.placeholder.com/500?text=Шкаф+3-дверный',
    },
    {
      'id': 34,
      'name': 'Кровать 160x200',
      'description': 'С деревянным основанием',
      'category': 'furniture',
      'price': 8999,
      'quantityOfGoods': 7,
      'productRating': 4.6,
      'image': 'https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?ixlib=rb-1.2.1&auto=format&fit=crop&w=500&q=60',
    },
    {
      'id': 35,
      'name': 'Тумбочка прикроватная',
      'description': 'С двумя ящиками',
      'category': 'furniture',
      'price': 2499,
      'quantityOfGoods': 12,
      'productRating': 4.4,
      'image': 'https://via.placeholder.com/500?text=Тумбочка+прикроватная',
    },
  ],
  'pharmacy': [
    {
      'id': 36,
      'name': 'Парацетамол',
      'description': '500мг, 20 таблеток',
      'category': 'pharmacy',
      'price': 89,
      'quantityOfGoods': 100,
      'productRating': 4.8,
      'image': 'https://via.placeholder.com/500?text=Парацетамол',
    },
    {
      'id': 37,
      'name': 'Витамин C',
      'description': 'Аскорбиновая кислота, 100шт',
      'category': 'pharmacy',
      'price': 299,
      'quantityOfGoods': 50,
      'productRating': 4.5,
      'image': 'https://via.placeholder.com/500?text=Витамин+C',
    },
    {
      'id': 38,
      'name': 'Термометр электронный',
      'description': 'Измерение за 10 секунд',
      'category': 'pharmacy',
      'price': 599,
      'quantityOfGoods': 20,
      'productRating': 4.6,
      'image': 'https://via.placeholder.com/500?text=Термометр+электронный',
    },
    {
      'id': 39,
      'name': 'Пластырь бактерицидный',
      'description': '20 штук в упаковке',
      'category': 'pharmacy',
      'price': 129,
      'quantityOfGoods': 70,
      'productRating': 4.3,
      'image': 'https://via.placeholder.com/500?text=Пластырь+бактерицидный',
    },
    {
      'id': 40,
      'name': 'Маска медицинская',
      'description': '50 штук, одноразовая',
      'category': 'pharmacy',
      'price': 399,
      'quantityOfGoods': 150,
      'productRating': 4.4,
      'image': 'https://via.placeholder.com/500?text=Маска+медицинская',
    },
  ],
  'hobbiesAndCreativity': [
    {
      'id': 41,
      'name': 'Набор для рисования',
      'description': 'Краски, кисти, холст',
      'category': 'hobbiesAndCreativity',
      'price': 1499,
      'quantityOfGoods': 25,
      'productRating': 4.7,
      'image': 'https://images.unsplash.com/photo-1541961017774-22349e4a1262?ixlib=rb-1.2.1&auto=format&fit=crop&w=500&q=60',
    },
    {
      'id': 42,
      'name': 'Конструктор Lego',
      'description': '500 деталей, классика',
      'category': 'hobbiesAndCreativity',
      'price': 3499,
      'quantityOfGoods': 15,
      'productRating': 4.9,
      'image': 'https://images.unsplash.com/photo-1587654780291-39c9404d746b?ixlib=rb-1.2.1&auto=format&fit=crop&w=500&q=60',
    },
    {
      'id': 43,
      'name': 'Пряжа для вязания',
      'description': '100% шерсть, 3 мотка',
      'category': 'hobbiesAndCreativity',
      'price': 599,
      'quantityOfGoods': 40,
      'productRating': 4.5,
      'image': 'https://images.unsplash.com/photo-1610392983074-dc0b5d93a0c4?ixlib=rb-1.2.1&auto=format&fit=crop&w=500&q=60',
    },
    {
      'id': 44,
      'name': 'Электрогитара',
      'description': 'Для начинающих',
      'category': 'hobbiesAndCreativity',
      'price': 8999,
      'quantityOfGoods': 6,
      'productRating': 4.6,
      'image': 'https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?ixlib=rb-1.2.1&auto=format&fit=crop&w=500&q=60',
    },
    {
      'id': 45,
      'name': 'Мольберт деревянный',
      'description': 'Настольный, складной',
      'category': 'hobbiesAndCreativity',
      'price': 1299,
      'quantityOfGoods': 10,
      'productRating': 4.4,
      'image': 'https://via.placeholder.com/500?text=Мольберт+деревянный',
    },
  ],
};

export const categoryItems: ICategoryItem[] = [
  {
    id: 1,
    type: CategoryEnum.clothesAndShoes,
    name: 'Одежда и обувь',
    image: 'https://cdn-icons-png.flaticon.com/512/1046/1046852.png',
  },
  {
    id: 2,
    type: CategoryEnum.householdGoods,
    name: 'Товары для дома',
    image: 'https://cdn-icons-png.flaticon.com/512/1046/1046857.png',
  },
  {
    id: 3,
    type: CategoryEnum.electronics,
    name: 'Электроника',
    image: 'https://cdn-icons-png.flaticon.com/512/1046/1046858.png',
  },
  {
    id: 4,
    type: CategoryEnum.householdAppliances,
    name: 'Бытовая техника',
    image: 'https://cdn-icons-png.flaticon.com/512/1046/1046859.png',
  },
  {
    id: 5,
    type: CategoryEnum.goodsForChildren,
    name: 'Товары для детей',
    image: 'https://cdn-icons-png.flaticon.com/512/1046/1046860.png',
  },
  {
    id: 6,
    type: CategoryEnum.constructionAndRenovation,
    name: 'Строительство и ремонт',
    image: 'https://cdn-icons-png.flaticon.com/512/1046/1046861.png',
  },
  {
    id: 7,
    type: CategoryEnum.furniture,
    name: 'Мебель',
    image: 'https://cdn-icons-png.flaticon.com/512/1046/1046862.png',
  },
  {
    id: 8,
    type: CategoryEnum.pharmacy,
    name: 'Аптека',
    image: 'https://cdn-icons-png.flaticon.com/512/1046/1046867.png',
  },
  {
    id: 9,
    type: CategoryEnum.hobbiesAndCreativity,
    name: 'Хобби и творчество',
    image: 'https://cdn-icons-png.flaticon.com/512/1046/1046864.png',
  },
];
