import { ProductListType } from './MockData.types';

// created by GPT
export const productList: ProductListType = {
  clothesAndShoes: [
    {
      id: 1,
      name: 'Кроссовки Nike',
      description: 'Удобные кроссовки для повседневной носки',
      category: 'clothesAndShoes',
      price: 5999,
      quantityOfGoods: 10,
      productRating: 4.5,
      image: 'https://example.com/nike-shoes.jpg',
    },
    {
      id: 2,
      name: 'Куртка зимняя',
      description: 'Теплая куртка с подкладкой',
      category: 'clothesAndShoes',
      price: 8999,
      quantityOfGoods: 7,
      productRating: 4.8,
      image: 'https://example.com/winter-jacket.jpg',
    },
    {
      id: 3,
      name: 'Футболка белая',
      description: 'Хлопковая футболка',
      category: 'clothesAndShoes',
      price: 799,
      quantityOfGoods: 50,
      productRating: 4.2,
      image: 'https://example.com/white-tshirt.jpg',
    },
    {
      id: 4,
      name: 'Джинсы мужские',
      description: 'Классические джинсы',
      category: 'clothesAndShoes',
      price: 2999,
      quantityOfGoods: 20,
      productRating: 4.4,
      image: 'https://example.com/jeans.jpg',
    },
    {
      id: 5,
      name: 'Ботинки кожаные',
      description: 'Натуральная кожа, зимние',
      category: 'clothesAndShoes',
      price: 6999,
      quantityOfGoods: 5,
      productRating: 4.7,
      image: 'https://example.com/leather-boots.jpg',
    },
  ],
  householdGoods: [
    {
      id: 6,
      name: 'Швабра с отжимом',
      description: 'Для удобной уборки пола',
      category: 'householdGoods',
      price: 1299,
      quantityOfGoods: 12,
      productRating: 4.3,
      image: 'https://example.com/mop.jpg',
    },
    {
      id: 7,
      name: 'Набор губок',
      description: '5 штук для мытья посуды',
      category: 'householdGoods',
      price: 199,
      quantityOfGoods: 100,
      productRating: 4.1,
      image: 'https://example.com/sponges.jpg',
    },
    {
      id: 8,
      name: 'Корзина для белья',
      description: 'Пластиковая корзина 45л',
      category: 'householdGoods',
      price: 899,
      quantityOfGoods: 15,
      productRating: 4.6,
      image: 'https://example.com/laundry-basket.jpg',
    },
    {
      id: 9,
      name: 'Контейнеры для хранения',
      description: 'Набор из 3 контейнеров',
      category: 'householdGoods',
      price: 499,
      quantityOfGoods: 25,
      productRating: 4.4,
      image: 'https://example.com/storage-boxes.jpg',
    },
    {
      id: 10,
      name: 'Сушилка для белья',
      description: 'Складная сушилка, 20м',
      category: 'householdGoods',
      price: 1799,
      quantityOfGoods: 8,
      productRating: 4.5,
      image: 'https://example.com/clothes-dryer.jpg',
    },
  ],
  electronics: [
    {
      id: 11,
      name: 'Смартфон Samsung',
      description: '128Гб, черный',
      category: 'electronics',
      price: 25999,
      quantityOfGoods: 30,
      productRating: 4.8,
      image: 'https://example.com/samsung-phone.jpg',
    },
    {
      id: 12,
      name: 'Наушники Bluetooth',
      description: 'Беспроводные с шумоподавлением',
      category: 'electronics',
      price: 3999,
      quantityOfGoods: 50,
      productRating: 4.6,
      image: 'https://example.com/bluetooth-headphones.jpg',
    },
    {
      id: 13,
      name: 'Повербанк 10000мАч',
      description: 'Компактный и мощный',
      category: 'electronics',
      price: 1499,
      quantityOfGoods: 80,
      productRating: 4.3,
      image: 'https://example.com/powerbank.jpg',
    },
    {
      id: 14,
      name: 'Монитор 24"',
      description: 'FullHD монитор',
      category: 'electronics',
      price: 7499,
      quantityOfGoods: 18,
      productRating: 4.7,
      image: 'https://example.com/monitor.jpg',
    },
    {
      id: 15,
      name: 'Клавиатура механическая',
      description: 'RGB подсветка',
      category: 'electronics',
      price: 2999,
      quantityOfGoods: 25,
      productRating: 4.5,
      image: 'https://example.com/keyboard.jpg',
    },
  ],
  householdAppliances: [
    {
      id: 16,
      name: 'Микроволновка',
      description: '20л, с грилем',
      category: 'householdAppliances',
      price: 5999,
      quantityOfGoods: 10,
      productRating: 4.5,
      image: 'https://example.com/microwave.jpg',
    },
    {
      id: 17,
      name: 'Пылесос циклонный',
      description: 'Мощный и компактный',
      category: 'householdAppliances',
      price: 7999,
      quantityOfGoods: 8,
      productRating: 4.6,
      image: 'https://example.com/vacuum.jpg',
    },
    {
      id: 18,
      name: 'Утюг с паром',
      description: 'Быстрый нагрев',
      category: 'householdAppliances',
      price: 2499,
      quantityOfGoods: 15,
      productRating: 4.2,
      image: 'https://example.com/iron.jpg',
    },
    {
      id: 19,
      name: 'Хлебопечка',
      description: '12 программ, таймер',
      category: 'householdAppliances',
      price: 5999,
      quantityOfGoods: 6,
      productRating: 4.4,
      image: 'https://example.com/breadmaker.jpg',
    },
    {
      id: 20,
      name: 'Электрочайник',
      description: '1.7л, автоотключение',
      category: 'householdAppliances',
      price: 1999,
      quantityOfGoods: 20,
      productRating: 4.7,
      image: 'https://example.com/kettle.jpg',
    },
  ],
  goodsForChildren: [
    {
      id: 21,
      name: 'Коляска прогулочная',
      description: 'Легкая и складная',
      category: 'goodsForChildren',
      price: 8999,
      quantityOfGoods: 5,
      productRating: 4.6,
      image: 'https://example.com/stroller.jpg',
    },
    {
      id: 22,
      name: 'Пеленки одноразовые',
      description: '60x60, упаковка 30шт',
      category: 'goodsForChildren',
      price: 799,
      quantityOfGoods: 40,
      productRating: 4.3,
      image: 'https://example.com/diapers.jpg',
    },
    {
      id: 23,
      name: 'Игрушка развивающая',
      description: 'Музыкальная с огоньками',
      category: 'goodsForChildren',
      price: 1499,
      quantityOfGoods: 20,
      productRating: 4.5,
      image: 'https://example.com/toy.jpg',
    },
    {
      id: 24,
      name: 'Стульчик для кормления',
      description: 'Съемный поднос, компактный',
      category: 'goodsForChildren',
      price: 3999,
      quantityOfGoods: 10,
      productRating: 4.4,
      image: 'https://example.com/highchair.jpg',
    },
    {
      id: 25,
      name: 'Ночник детский',
      description: 'Проектор звездного неба',
      category: 'goodsForChildren',
      price: 999,
      quantityOfGoods: 30,
      productRating: 4.6,
      image: 'https://example.com/nightlight.jpg',
    },
  ],
  constructionAndRenovation: [
    {
      id: 26,
      name: 'Перфоратор Bosch',
      description: 'Мощный инструмент для ремонта',
      category: 'constructionAndRenovation',
      price: 9999,
      quantityOfGoods: 12,
      productRating: 4.7,
      image: 'https://example.com/perforator.jpg',
    },
    {
      id: 27,
      name: 'Обои виниловые',
      description: 'Рулон 10м, с узором',
      category: 'constructionAndRenovation',
      price: 599,
      quantityOfGoods: 40,
      productRating: 4.4,
      image: 'https://example.com/wallpaper.jpg',
    },
    {
      id: 28,
      name: 'Краска интерьерная',
      description: '10л, белая',
      category: 'constructionAndRenovation',
      price: 1299,
      quantityOfGoods: 30,
      productRating: 4.5,
      image: 'https://example.com/paint.jpg',
    },
    {
      id: 29,
      name: 'Плитка керамическая',
      description: '20x20, упаковка 1.2м²',
      category: 'constructionAndRenovation',
      price: 899,
      quantityOfGoods: 50,
      productRating: 4.6,
      image: 'https://example.com/tiles.jpg',
    },
    {
      id: 30,
      name: 'Герметик силиконовый',
      description: 'Белый, тюбик 300мл',
      category: 'constructionAndRenovation',
      price: 299,
      quantityOfGoods: 60,
      productRating: 4.2,
      image: 'https://example.com/sealant.jpg',
    },
  ],
  furniture: [
    {
      id: 31,
      name: 'Стол письменный',
      description: 'Деревянный, 120x60',
      category: 'furniture',
      price: 5999,
      quantityOfGoods: 10,
      productRating: 4.5,
      image: 'https://example.com/desk.jpg',
    },
    {
      id: 32,
      name: 'Кресло офисное',
      description: 'С эргономичной спинкой',
      category: 'furniture',
      price: 4999,
      quantityOfGoods: 8,
      productRating: 4.6,
      image: 'https://example.com/office-chair.jpg',
    },
    {
      id: 33,
      name: 'Шкаф 3-дверный',
      description: 'С зеркалом и полками',
      category: 'furniture',
      price: 10999,
      quantityOfGoods: 5,
      productRating: 4.7,
      image: 'https://example.com/wardrobe.jpg',
    },
    {
      id: 34,
      name: 'Кровать 160x200',
      description: 'С деревянным основанием',
      category: 'furniture',
      price: 8999,
      quantityOfGoods: 7,
      productRating: 4.6,
      image: 'https://example.com/bed.jpg',
    },
    {
      id: 35,
      name: 'Тумбочка прикроватная',
      description: 'С двумя ящиками',
      category: 'furniture',
      price: 2499,
      quantityOfGoods: 12,
      productRating: 4.4,
      image: 'https://example.com/nightstand.jpg',
    },
  ],
  pharmacy: [
    {
      id: 36,
      name: 'Парацетамол',
      description: '500мг, 20 таблеток',
      category: 'pharmacy',
      price: 89,
      quantityOfGoods: 100,
      productRating: 4.8,
      image: 'https://example.com/paracetamol.jpg',
    },
    {
      id: 37,
      name: 'Витамин C',
      description: 'Аскорбиновая кислота, 100шт',
      category: 'pharmacy',
      price: 299,
      quantityOfGoods: 50,
      productRating: 4.5,
      image: 'https://example.com/vitamin-c.jpg',
    },
    {
      id: 38,
      name: 'Термометр электронный',
      description: 'Измерение за 10 секунд',
      category: 'pharmacy',
      price: 599,
      quantityOfGoods: 20,
      productRating: 4.6,
      image: 'https://example.com/thermometer.jpg',
    },
    {
      id: 39,
      name: 'Пластырь бактерицидный',
      description: '20 штук в упаковке',
      category: 'pharmacy',
      price: 129,
      quantityOfGoods: 70,
      productRating: 4.3,
      image: 'https://example.com/plaster.jpg',
    },
    {
      id: 40,
      name: 'Маска медицинская',
      description: '50 штук, одноразовая',
      category: 'pharmacy',
      price: 399,
      quantityOfGoods: 150,
      productRating: 4.4,
      image: 'https://example.com/mask.jpg',
    },
  ],
  hobbiesAndCreativity: [
    {
      id: 41,
      name: 'Набор для рисования',
      description: 'Краски, кисти, холст',
      category: 'hobbiesAndCreativity',
      price: 1499,
      quantityOfGoods: 25,
      productRating: 4.7,
      image: 'https://example.com/painting-set.jpg',
    },
    {
      id: 42,
      name: 'Конструктор Lego',
      description: '500 деталей, классика',
      category: 'hobbiesAndCreativity',
      price: 3499,
      quantityOfGoods: 15,
      productRating: 4.9,
      image: 'https://example.com/lego.jpg',
    },
    {
      id: 43,
      name: 'Пряжа для вязания',
      description: '100% шерсть, 3 мотка',
      category: 'hobbiesAndCreativity',
      price: 599,
      quantityOfGoods: 40,
      productRating: 4.5,
      image: 'https://example.com/yarn.jpg',
    },
    {
      id: 44,
      name: 'Электрогитара',
      description: 'Для начинающих',
      category: 'hobbiesAndCreativity',
      price: 8999,
      quantityOfGoods: 6,
      productRating: 4.6,
      image: 'https://example.com/guitar.jpg',
    },
    {
      id: 45,
      name: 'Мольберт деревянный',
      description: 'Настольный, складной',
      category: 'hobbiesAndCreativity',
      price: 1299,
      quantityOfGoods: 10,
      productRating: 4.4,
      image: 'https://example.com/easel.jpg',
    },
  ],
};

